import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  /**
   * The authoring tool is a self-contained workspace with its own conventions and test/typecheck gates;
   * it is extraction-destined (see wayfinder #298).
   */
  ignoreWorkspaces: ['tools/svg-authoring'],
  workspaces: {
    '.': {
      entry: [
        /* TanStack Start file-based routing: routes are loaded by the router
           plugin, not imported anywhere knip can see. */
        'src/app/router.tsx',
        'src/app/routes/**/{index,route,*.route,__root}.tsx',
        /* #907 deliberately lands the Rulebook data doorway before #909 adopts it in the editor route. */
        'src/app/db/rulebooks.ts',
        // Built via workers/publisher/vite.config.ts (publisher-capture.html input).
        'src/app/print/capture/publisher-entry.tsx',
        // Worker entry, referenced from workers/publisher/wrangler.jsonc.
        'workers/publisher/index.ts',
        /* Standalone scripts run ad hoc with `bun run ./scripts/...`. Deliberately
           not scripts/lib/**, where helpers must be imported to count as used. */
        'scripts/*.{ts,mjs}',
      ],
      /**
       * Non-default vite config locations (custom `config` overrides the plugin default, so the root config must be listed too).
       * The .storybook one is referenced by string from .storybook/main.ts (viteConfigPath).
       */
      vite: {
        config: ['vite.config.ts', 'workers/publisher/vite.config.ts', '.storybook/vite.config.ts'],
      },
      /**
       * Dev-toggle devtools: imported only from commented-out code in src/app/routes/__root.tsx and vite.config.ts, kept for flipping on during debugging.
       */
      ignoreDependencies: ['@tanstack/react-devtools', '@tanstack/react-router-devtools', '@tanstack/devtools-vite'],
      ignore: [
        // Generated by the router plugin.
        'src/app/routeTree.gen.ts',
      ],
    },
  },
};

export default config;
