import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  /**
   * The authoring tool is a self-contained workspace with its own conventions and test/typecheck gates;
   * it is extraction-destined (see wayfinder #298).
   */
  ignoreWorkspaces: ['tools/svg-authoring'],
  workspaces: {
    '.': {
      entry: [
        /* TanStack Start file-based routing: routes are loaded by the router
           plugin, not imported anywhere knip can see. */
        'src/app/router.tsx',
        'src/app/routes/start.ts',
        'src/app/routes/**/{index,route,*.route,__root}.tsx',
        /* Scene pragmas load these JSX compiler entries. */
        'src/app/widgets/tabletop/three-jsx/*.{ts,tsx}',
        /* Type fixtures are checked by tsc without a runtime importer. */
        'src/**/*.typecheck.{ts,tsx}',
        // Built via workers/publisher/vite.config.ts (publisher-capture.html input).
        'src/app/print/capture/publisher-entry.tsx',
        // Worker entry, referenced from workers/publisher/wrangler.jsonc.
        'workers/publisher/index.ts',
        'workers/game/index.ts',
        /* The isolated stack's load runs start the game Worker from this entry by filename. */
        'workers/game/load-entry.ts',
        /* Native workerd tests bundle these entries with esbuild by filename. */
        'workers/game/authorization.native.fixture.ts',
        'workers/game/game-room.native.fixture.ts',
        'workers/game/homepage.native.fixture.ts',
        'workers/game/load-limits.native.fixture.ts',
        /* Standalone scripts run ad hoc with `bun run ./scripts/...`. Deliberately
           not scripts/lib/**, where helpers must be imported to count as used. */
        'scripts/*.{ts,mjs}',
        /* esbuild bundles the load runner by filename before the isolated stack launches it. */
        'scripts/play-load/run.mjs',
        /* A service worker, registered by its URL from .storybook/storyImages.ts. */
        '.storybook/static/story-images.sw.js',
      ],
      /**
       * Non-default vite config locations (custom `config` overrides the plugin default, so the root config must be listed too).
       * The .storybook one is referenced by string from .storybook/main.ts (viteConfigPath).
       */
      vite: {
        config: ['vite.config.ts', 'workers/publisher/vite.config.ts', '.storybook/vite.config.ts'],
      },
      /* The app's Vite aliases are an array, which knip's Vite plugin does not read; this one names a source file. */
      paths: {
        '@app/widgets/tabletop/three-jsx': ['src/app/widgets/tabletop/three-jsx/jsx-runtime.ts'],
        'rulebook-html-renderer-runtime': ['src/app/print/rulebookHtmlRuntime.ts'],
        'application-ssr-runtime': ['node_modules/@tanstack/react-start/dist/default-entry/esm/server.js'],
      },
      /**
       * Dev-toggle devtools: imported only from commented-out code in src/app/routes/__root.tsx and vite.config.ts, kept for flipping on during debugging.
       */
      ignoreDependencies: [
        '@tanstack/react-devtools',
        '@tanstack/react-router-devtools',
        '@tanstack/devtools-vite',
        /* workerd provides cloudflare:workers; there is no npm dependency. */
        'cloudflare',
      ],
      ignore: [
        // Generated by the router plugin.
        'src/app/routeTree.gen.ts',
      ],
    },
  },
};

export default config;
