import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: [
    // TanStack Start file-based routing: routes are loaded by the router
    // plugin, not imported anywhere knip can see.
    'src/app/router.tsx',
    'src/app/routes/**/*.tsx',
    // Built via workers/publisher/vite.config.ts (publisher-capture.html input).
    'src/app/capture/publisher-entry.tsx',
    // Worker entry, referenced from workers/publisher/wrangler.jsonc.
    'workers/publisher/index.ts',
    // Standalone scripts run ad hoc with `bun run ./scripts/...`.
    // Deliberately not scripts/lib/** — helpers there must be imported to count as used.
    'scripts/*.{ts,mjs}',
    // Referenced by string from .storybook/main.ts (viteConfigPath).
    '.storybook/vite.config.ts',
  ],
  // Dev-toggle devtools: imported only from commented-out code in
  // src/app/routes/__root.tsx and vite.config.ts, kept for flipping on
  // during debugging.
  ignoreDependencies: [
    '@tanstack/react-devtools',
    '@tanstack/react-router-devtools',
    '@tanstack/devtools-vite',
  ],
  ignore: [
    // Research spikes, intentionally not wired into the app.
    'docs/**',
    // Generated by the router plugin.
    'src/app/routeTree.gen.ts',
  ],
};

export default config;
