/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app.route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteRouteImport } from './routes/_app/$.route'
import { Route as App_iconsRouteRouteImport } from './routes/_app/[_]_icons.route'
import { Route as App_jobsRouteRouteImport } from './routes/_app/[_]_jobs.route'
import { Route as AuthOauthRouteRouteImport } from './routes/auth/oauth.route'
import { Route as AppAdminMigrationsRouteRouteImport } from './routes/_app/admin/migrations.route'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppAuthIndexRouteImport } from './routes/_app/auth/index'
import { Route as AppAuthErrorRouteRouteImport } from './routes/_app/auth/error.route'
import { Route as AppAuthLoginRouteRouteImport } from './routes/_app/auth/login.route'
import { Route as AppFactionsIndexRouteImport } from './routes/_app/factions/index'
import { Route as AppFactionsCreateRouteRouteImport } from './routes/_app/factions/create.route'
import { Route as AppFuturePlansIndexRouteImport } from './routes/_app/future-plans/index'
import { Route as AppGroupsGroupSlugRouteRouteImport } from './routes/_app/groups/$groupSlug.route'
import { Route as AppGroupsCreateRouteRouteImport } from './routes/_app/groups/create.route'
import { Route as AppPrivacyIndexRouteImport } from './routes/_app/privacy/index'
import { Route as AppProfilesIndexRouteImport } from './routes/_app/profiles/index'
import { Route as AppRulesetsIndexRouteImport } from './routes/_app/rulesets/index'
import { Route as AppRulesetsRulesetSlugRouteRouteImport } from './routes/_app/rulesets/$rulesetSlug.route'
import { Route as AppRulesetsCreateRouteRouteImport } from './routes/_app/rulesets/create.route'
import { Route as PreviewSheetFactionSlugRouteRouteImport } from './routes/preview/sheet/$factionSlug.route'
import { Route as AppAssetsTypeIndexRouteImport } from './routes/_app/assets/$type/index'
import { Route as AppFactionsFactionIdIndexRouteImport } from './routes/_app/factions/$factionId/index'
import { Route as AppFactionsFactionIdEditRouteRouteImport } from './routes/_app/factions/$factionId/edit.route'
import { Route as AppGroupsGroupSlugIndexRouteImport } from './routes/_app/groups/$groupSlug/index'
import { Route as AppGroupsGroupSlugEditRouteRouteImport } from './routes/_app/groups/$groupSlug/edit.route'
import { Route as AppProfilesProfileSlugIndexRouteImport } from './routes/_app/profiles/$profileSlug/index'
import { Route as AppProfilesProfileSlugDeleteRouteRouteImport } from './routes/_app/profiles/$profileSlug/delete.route'
import { Route as AppProfilesProfileSlugEditRouteRouteImport } from './routes/_app/profiles/$profileSlug/edit.route'
import { Route as AppRulesetsRulesetSlugIndexRouteImport } from './routes/_app/rulesets/$rulesetSlug/index'
import { Route as AppRulesetsRulesetSlugEditRouteRouteImport } from './routes/_app/rulesets/$rulesetSlug/edit.route'
import { Route as AppAssetsTypeSlugIndexRouteImport } from './routes/_app/assets/$type/$slug/index'
import { Route as AppAssetsTypeCreateIndexRouteImport } from './routes/_app/assets/$type/create/index'
import { Route as AppRulesetsRulesetSlugFaqQuestionSlugRouteRouteImport } from './routes/_app/rulesets/$rulesetSlug/faq/$questionSlug.route'
import { Route as AppRulesetsRulesetSlugFaqCreateRouteRouteImport } from './routes/_app/rulesets/$rulesetSlug/faq/create.route'
import { Route as AppRulesetsRulesetSlugRulebooksCreateRouteRouteImport } from './routes/_app/rulesets/$rulesetSlug/rulebooks/create.route'
import { Route as AppAssetsTypeSlugEditIndexRouteImport } from './routes/_app/assets/$type/$slug/edit/index'
import { Route as AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRouteImport } from './routes/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/index'
import { Route as AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRouteImport } from './routes/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit.route'
import { Route as AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRouteImport } from './routes/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions.route'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSplatRouteRoute = AppSplatRouteRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const App_iconsRouteRoute = App_iconsRouteRouteImport.update({
  id: '/__icons',
  path: '/__icons',
  getParentRoute: () => AppRouteRoute,
} as any)
const App_jobsRouteRoute = App_jobsRouteRouteImport.update({
  id: '/__jobs',
  path: '/__jobs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthOauthRouteRoute = AuthOauthRouteRouteImport.update({
  id: '/auth/oauth',
  path: '/auth/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminMigrationsRouteRoute = AppAdminMigrationsRouteRouteImport.update({
  id: '/admin/migrations',
  path: '/admin/migrations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthIndexRoute = AppAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthErrorRouteRoute = AppAuthErrorRouteRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthLoginRouteRoute = AppAuthLoginRouteRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFactionsIndexRoute = AppFactionsIndexRouteImport.update({
  id: '/factions/',
  path: '/factions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFactionsCreateRouteRoute = AppFactionsCreateRouteRouteImport.update({
  id: '/factions/create',
  path: '/factions/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFuturePlansIndexRoute = AppFuturePlansIndexRouteImport.update({
  id: '/future-plans/',
  path: '/future-plans/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsGroupSlugRouteRoute = AppGroupsGroupSlugRouteRouteImport.update({
  id: '/groups/$groupSlug',
  path: '/groups/$groupSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsCreateRouteRoute = AppGroupsCreateRouteRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrivacyIndexRoute = AppPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfilesIndexRoute = AppProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRulesetsIndexRoute = AppRulesetsIndexRouteImport.update({
  id: '/rulesets/',
  path: '/rulesets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRulesetsRulesetSlugRouteRoute =
  AppRulesetsRulesetSlugRouteRouteImport.update({
    id: '/rulesets/$rulesetSlug',
    path: '/rulesets/$rulesetSlug',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppRulesetsCreateRouteRoute = AppRulesetsCreateRouteRouteImport.update({
  id: '/rulesets/create',
  path: '/rulesets/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const PreviewSheetFactionSlugRouteRoute =
  PreviewSheetFactionSlugRouteRouteImport.update({
    id: '/preview/sheet/$factionSlug',
    path: '/preview/sheet/$factionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAssetsTypeIndexRoute = AppAssetsTypeIndexRouteImport.update({
  id: '/assets/$type/',
  path: '/assets/$type/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFactionsFactionIdIndexRoute =
  AppFactionsFactionIdIndexRouteImport.update({
    id: '/factions/$factionId/',
    path: '/factions/$factionId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppFactionsFactionIdEditRouteRoute =
  AppFactionsFactionIdEditRouteRouteImport.update({
    id: '/factions/$factionId/edit',
    path: '/factions/$factionId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppGroupsGroupSlugIndexRoute = AppGroupsGroupSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroupsGroupSlugRouteRoute,
} as any)
const AppGroupsGroupSlugEditRouteRoute =
  AppGroupsGroupSlugEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppGroupsGroupSlugRouteRoute,
  } as any)
const AppProfilesProfileSlugIndexRoute =
  AppProfilesProfileSlugIndexRouteImport.update({
    id: '/profiles/$profileSlug/',
    path: '/profiles/$profileSlug/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProfilesProfileSlugDeleteRouteRoute =
  AppProfilesProfileSlugDeleteRouteRouteImport.update({
    id: '/profiles/$profileSlug/delete',
    path: '/profiles/$profileSlug/delete',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProfilesProfileSlugEditRouteRoute =
  AppProfilesProfileSlugEditRouteRouteImport.update({
    id: '/profiles/$profileSlug/edit',
    path: '/profiles/$profileSlug/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppRulesetsRulesetSlugIndexRoute =
  AppRulesetsRulesetSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppRulesetsRulesetSlugRouteRoute,
  } as any)
const AppRulesetsRulesetSlugEditRouteRoute =
  AppRulesetsRulesetSlugEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppRulesetsRulesetSlugRouteRoute,
  } as any)
const AppAssetsTypeSlugIndexRoute = AppAssetsTypeSlugIndexRouteImport.update({
  id: '/assets/$type/$slug/',
  path: '/assets/$type/$slug/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssetsTypeCreateIndexRoute =
  AppAssetsTypeCreateIndexRouteImport.update({
    id: '/assets/$type/create/',
    path: '/assets/$type/create/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppRulesetsRulesetSlugFaqQuestionSlugRouteRoute =
  AppRulesetsRulesetSlugFaqQuestionSlugRouteRouteImport.update({
    id: '/faq/$questionSlug',
    path: '/faq/$questionSlug',
    getParentRoute: () => AppRulesetsRulesetSlugRouteRoute,
  } as any)
const AppRulesetsRulesetSlugFaqCreateRouteRoute =
  AppRulesetsRulesetSlugFaqCreateRouteRouteImport.update({
    id: '/faq/create',
    path: '/faq/create',
    getParentRoute: () => AppRulesetsRulesetSlugRouteRoute,
  } as any)
const AppRulesetsRulesetSlugRulebooksCreateRouteRoute =
  AppRulesetsRulesetSlugRulebooksCreateRouteRouteImport.update({
    id: '/rulebooks/create',
    path: '/rulebooks/create',
    getParentRoute: () => AppRulesetsRulesetSlugRouteRoute,
  } as any)
const AppAssetsTypeSlugEditIndexRoute =
  AppAssetsTypeSlugEditIndexRouteImport.update({
    id: '/assets/$type/$slug/edit/',
    path: '/assets/$type/$slug/edit/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRoute =
  AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRouteImport.update({
    id: '/rulebooks/$rulebookSlug/',
    path: '/rulebooks/$rulebookSlug/',
    getParentRoute: () => AppRulesetsRulesetSlugRouteRoute,
  } as any)
const AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRoute =
  AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRouteImport.update({
    id: '/rulebooks/$rulebookSlug/edit',
    path: '/rulebooks/$rulebookSlug/edit',
    getParentRoute: () => AppRulesetsRulesetSlugRouteRoute,
  } as any)
const AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRoute =
  AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRouteImport.update({
    id: '/rulebooks/$rulebookSlug/editions',
    path: '/rulebooks/$rulebookSlug/editions',
    getParentRoute: () => AppRulesetsRulesetSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$': typeof AppSplatRouteRoute
  '/__icons': typeof App_iconsRouteRoute
  '/__jobs': typeof App_jobsRouteRoute
  '/auth/oauth': typeof AuthOauthRouteRoute
  '/admin/migrations': typeof AppAdminMigrationsRouteRoute
  '/auth/error': typeof AppAuthErrorRouteRoute
  '/auth/login': typeof AppAuthLoginRouteRoute
  '/factions/create': typeof AppFactionsCreateRouteRoute
  '/groups/$groupSlug': typeof AppGroupsGroupSlugRouteRouteWithChildren
  '/groups/create': typeof AppGroupsCreateRouteRoute
  '/rulesets/$rulesetSlug': typeof AppRulesetsRulesetSlugRouteRouteWithChildren
  '/rulesets/create': typeof AppRulesetsCreateRouteRoute
  '/preview/sheet/$factionSlug': typeof PreviewSheetFactionSlugRouteRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/auth/': typeof AppAuthIndexRoute
  '/factions/': typeof AppFactionsIndexRoute
  '/future-plans/': typeof AppFuturePlansIndexRoute
  '/privacy/': typeof AppPrivacyIndexRoute
  '/profiles/': typeof AppProfilesIndexRoute
  '/rulesets/': typeof AppRulesetsIndexRoute
  '/factions/$factionId/edit': typeof AppFactionsFactionIdEditRouteRoute
  '/groups/$groupSlug/edit': typeof AppGroupsGroupSlugEditRouteRoute
  '/profiles/$profileSlug/delete': typeof AppProfilesProfileSlugDeleteRouteRoute
  '/profiles/$profileSlug/edit': typeof AppProfilesProfileSlugEditRouteRoute
  '/rulesets/$rulesetSlug/edit': typeof AppRulesetsRulesetSlugEditRouteRoute
  '/assets/$type/': typeof AppAssetsTypeIndexRoute
  '/factions/$factionId/': typeof AppFactionsFactionIdIndexRoute
  '/groups/$groupSlug/': typeof AppGroupsGroupSlugIndexRoute
  '/profiles/$profileSlug/': typeof AppProfilesProfileSlugIndexRoute
  '/rulesets/$rulesetSlug/': typeof AppRulesetsRulesetSlugIndexRoute
  '/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRouteRoute
  '/rulesets/$rulesetSlug/faq/create': typeof AppRulesetsRulesetSlugFaqCreateRouteRoute
  '/rulesets/$rulesetSlug/rulebooks/create': typeof AppRulesetsRulesetSlugRulebooksCreateRouteRoute
  '/assets/$type/$slug/': typeof AppAssetsTypeSlugIndexRoute
  '/assets/$type/create/': typeof AppAssetsTypeCreateIndexRoute
  '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRoute
  '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRoute
  '/assets/$type/$slug/edit/': typeof AppAssetsTypeSlugEditIndexRoute
  '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof AppSplatRouteRoute
  '/__icons': typeof App_iconsRouteRoute
  '/__jobs': typeof App_jobsRouteRoute
  '/auth/oauth': typeof AuthOauthRouteRoute
  '/': typeof AppIndexRoute
  '/admin/migrations': typeof AppAdminMigrationsRouteRoute
  '/auth/error': typeof AppAuthErrorRouteRoute
  '/auth/login': typeof AppAuthLoginRouteRoute
  '/factions/create': typeof AppFactionsCreateRouteRoute
  '/groups/create': typeof AppGroupsCreateRouteRoute
  '/rulesets/create': typeof AppRulesetsCreateRouteRoute
  '/preview/sheet/$factionSlug': typeof PreviewSheetFactionSlugRouteRoute
  '/assets': typeof AppAssetsIndexRoute
  '/auth': typeof AppAuthIndexRoute
  '/factions': typeof AppFactionsIndexRoute
  '/future-plans': typeof AppFuturePlansIndexRoute
  '/privacy': typeof AppPrivacyIndexRoute
  '/profiles': typeof AppProfilesIndexRoute
  '/rulesets': typeof AppRulesetsIndexRoute
  '/factions/$factionId/edit': typeof AppFactionsFactionIdEditRouteRoute
  '/groups/$groupSlug/edit': typeof AppGroupsGroupSlugEditRouteRoute
  '/profiles/$profileSlug/delete': typeof AppProfilesProfileSlugDeleteRouteRoute
  '/profiles/$profileSlug/edit': typeof AppProfilesProfileSlugEditRouteRoute
  '/rulesets/$rulesetSlug/edit': typeof AppRulesetsRulesetSlugEditRouteRoute
  '/assets/$type': typeof AppAssetsTypeIndexRoute
  '/factions/$factionId': typeof AppFactionsFactionIdIndexRoute
  '/groups/$groupSlug': typeof AppGroupsGroupSlugIndexRoute
  '/profiles/$profileSlug': typeof AppProfilesProfileSlugIndexRoute
  '/rulesets/$rulesetSlug': typeof AppRulesetsRulesetSlugIndexRoute
  '/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRouteRoute
  '/rulesets/$rulesetSlug/faq/create': typeof AppRulesetsRulesetSlugFaqCreateRouteRoute
  '/rulesets/$rulesetSlug/rulebooks/create': typeof AppRulesetsRulesetSlugRulebooksCreateRouteRoute
  '/assets/$type/$slug': typeof AppAssetsTypeSlugIndexRoute
  '/assets/$type/create': typeof AppAssetsTypeCreateIndexRoute
  '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRoute
  '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRoute
  '/assets/$type/$slug/edit': typeof AppAssetsTypeSlugEditIndexRoute
  '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/$': typeof AppSplatRouteRoute
  '/_app/__icons': typeof App_iconsRouteRoute
  '/_app/__jobs': typeof App_jobsRouteRoute
  '/auth/oauth': typeof AuthOauthRouteRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/migrations': typeof AppAdminMigrationsRouteRoute
  '/_app/auth/error': typeof AppAuthErrorRouteRoute
  '/_app/auth/login': typeof AppAuthLoginRouteRoute
  '/_app/factions/create': typeof AppFactionsCreateRouteRoute
  '/_app/groups/$groupSlug': typeof AppGroupsGroupSlugRouteRouteWithChildren
  '/_app/groups/create': typeof AppGroupsCreateRouteRoute
  '/_app/rulesets/$rulesetSlug': typeof AppRulesetsRulesetSlugRouteRouteWithChildren
  '/_app/rulesets/create': typeof AppRulesetsCreateRouteRoute
  '/preview/sheet/$factionSlug': typeof PreviewSheetFactionSlugRouteRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/auth/': typeof AppAuthIndexRoute
  '/_app/factions/': typeof AppFactionsIndexRoute
  '/_app/future-plans/': typeof AppFuturePlansIndexRoute
  '/_app/privacy/': typeof AppPrivacyIndexRoute
  '/_app/profiles/': typeof AppProfilesIndexRoute
  '/_app/rulesets/': typeof AppRulesetsIndexRoute
  '/_app/factions/$factionId/edit': typeof AppFactionsFactionIdEditRouteRoute
  '/_app/groups/$groupSlug/edit': typeof AppGroupsGroupSlugEditRouteRoute
  '/_app/profiles/$profileSlug/delete': typeof AppProfilesProfileSlugDeleteRouteRoute
  '/_app/profiles/$profileSlug/edit': typeof AppProfilesProfileSlugEditRouteRoute
  '/_app/rulesets/$rulesetSlug/edit': typeof AppRulesetsRulesetSlugEditRouteRoute
  '/_app/assets/$type/': typeof AppAssetsTypeIndexRoute
  '/_app/factions/$factionId/': typeof AppFactionsFactionIdIndexRoute
  '/_app/groups/$groupSlug/': typeof AppGroupsGroupSlugIndexRoute
  '/_app/profiles/$profileSlug/': typeof AppProfilesProfileSlugIndexRoute
  '/_app/rulesets/$rulesetSlug/': typeof AppRulesetsRulesetSlugIndexRoute
  '/_app/rulesets/$rulesetSlug/faq/$questionSlug': typeof AppRulesetsRulesetSlugFaqQuestionSlugRouteRoute
  '/_app/rulesets/$rulesetSlug/faq/create': typeof AppRulesetsRulesetSlugFaqCreateRouteRoute
  '/_app/rulesets/$rulesetSlug/rulebooks/create': typeof AppRulesetsRulesetSlugRulebooksCreateRouteRoute
  '/_app/assets/$type/$slug/': typeof AppAssetsTypeSlugIndexRoute
  '/_app/assets/$type/create/': typeof AppAssetsTypeCreateIndexRoute
  '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRoute
  '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRoute
  '/_app/assets/$type/$slug/edit/': typeof AppAssetsTypeSlugEditIndexRoute
  '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/': typeof AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/__icons'
    | '/__jobs'
    | '/auth/oauth'
    | '/admin/migrations'
    | '/auth/error'
    | '/auth/login'
    | '/factions/create'
    | '/groups/$groupSlug'
    | '/groups/create'
    | '/rulesets/$rulesetSlug'
    | '/rulesets/create'
    | '/preview/sheet/$factionSlug'
    | '/assets/'
    | '/auth/'
    | '/factions/'
    | '/future-plans/'
    | '/privacy/'
    | '/profiles/'
    | '/rulesets/'
    | '/factions/$factionId/edit'
    | '/groups/$groupSlug/edit'
    | '/profiles/$profileSlug/delete'
    | '/profiles/$profileSlug/edit'
    | '/rulesets/$rulesetSlug/edit'
    | '/assets/$type/'
    | '/factions/$factionId/'
    | '/groups/$groupSlug/'
    | '/profiles/$profileSlug/'
    | '/rulesets/$rulesetSlug/'
    | '/rulesets/$rulesetSlug/faq/$questionSlug'
    | '/rulesets/$rulesetSlug/faq/create'
    | '/rulesets/$rulesetSlug/rulebooks/create'
    | '/assets/$type/$slug/'
    | '/assets/$type/create/'
    | '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit'
    | '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions'
    | '/assets/$type/$slug/edit/'
    | '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/__icons'
    | '/__jobs'
    | '/auth/oauth'
    | '/'
    | '/admin/migrations'
    | '/auth/error'
    | '/auth/login'
    | '/factions/create'
    | '/groups/create'
    | '/rulesets/create'
    | '/preview/sheet/$factionSlug'
    | '/assets'
    | '/auth'
    | '/factions'
    | '/future-plans'
    | '/privacy'
    | '/profiles'
    | '/rulesets'
    | '/factions/$factionId/edit'
    | '/groups/$groupSlug/edit'
    | '/profiles/$profileSlug/delete'
    | '/profiles/$profileSlug/edit'
    | '/rulesets/$rulesetSlug/edit'
    | '/assets/$type'
    | '/factions/$factionId'
    | '/groups/$groupSlug'
    | '/profiles/$profileSlug'
    | '/rulesets/$rulesetSlug'
    | '/rulesets/$rulesetSlug/faq/$questionSlug'
    | '/rulesets/$rulesetSlug/faq/create'
    | '/rulesets/$rulesetSlug/rulebooks/create'
    | '/assets/$type/$slug'
    | '/assets/$type/create'
    | '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit'
    | '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions'
    | '/assets/$type/$slug/edit'
    | '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/$'
    | '/_app/__icons'
    | '/_app/__jobs'
    | '/auth/oauth'
    | '/_app/'
    | '/_app/admin/migrations'
    | '/_app/auth/error'
    | '/_app/auth/login'
    | '/_app/factions/create'
    | '/_app/groups/$groupSlug'
    | '/_app/groups/create'
    | '/_app/rulesets/$rulesetSlug'
    | '/_app/rulesets/create'
    | '/preview/sheet/$factionSlug'
    | '/_app/assets/'
    | '/_app/auth/'
    | '/_app/factions/'
    | '/_app/future-plans/'
    | '/_app/privacy/'
    | '/_app/profiles/'
    | '/_app/rulesets/'
    | '/_app/factions/$factionId/edit'
    | '/_app/groups/$groupSlug/edit'
    | '/_app/profiles/$profileSlug/delete'
    | '/_app/profiles/$profileSlug/edit'
    | '/_app/rulesets/$rulesetSlug/edit'
    | '/_app/assets/$type/'
    | '/_app/factions/$factionId/'
    | '/_app/groups/$groupSlug/'
    | '/_app/profiles/$profileSlug/'
    | '/_app/rulesets/$rulesetSlug/'
    | '/_app/rulesets/$rulesetSlug/faq/$questionSlug'
    | '/_app/rulesets/$rulesetSlug/faq/create'
    | '/_app/rulesets/$rulesetSlug/rulebooks/create'
    | '/_app/assets/$type/$slug/'
    | '/_app/assets/$type/create/'
    | '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit'
    | '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions'
    | '/_app/assets/$type/$slug/edit/'
    | '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthOauthRouteRoute: typeof AuthOauthRouteRoute
  PreviewSheetFactionSlugRouteRoute: typeof PreviewSheetFactionSlugRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/__icons': {
      id: '/_app/__icons'
      path: '/__icons'
      fullPath: '/__icons'
      preLoaderRoute: typeof App_iconsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/__jobs': {
      id: '/_app/__jobs'
      path: '/__jobs'
      fullPath: '/__jobs'
      preLoaderRoute: typeof App_jobsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/oauth': {
      id: '/auth/oauth'
      path: '/auth/oauth'
      fullPath: '/auth/oauth'
      preLoaderRoute: typeof AuthOauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/migrations': {
      id: '/_app/admin/migrations'
      path: '/admin/migrations'
      fullPath: '/admin/migrations'
      preLoaderRoute: typeof AppAdminMigrationsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/auth/': {
      id: '/_app/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AppAuthIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/auth/error': {
      id: '/_app/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AppAuthErrorRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/auth/login': {
      id: '/_app/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AppAuthLoginRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/factions/': {
      id: '/_app/factions/'
      path: '/factions'
      fullPath: '/factions/'
      preLoaderRoute: typeof AppFactionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/factions/create': {
      id: '/_app/factions/create'
      path: '/factions/create'
      fullPath: '/factions/create'
      preLoaderRoute: typeof AppFactionsCreateRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/future-plans/': {
      id: '/_app/future-plans/'
      path: '/future-plans'
      fullPath: '/future-plans/'
      preLoaderRoute: typeof AppFuturePlansIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/groups/$groupSlug': {
      id: '/_app/groups/$groupSlug'
      path: '/groups/$groupSlug'
      fullPath: '/groups/$groupSlug'
      preLoaderRoute: typeof AppGroupsGroupSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/groups/create': {
      id: '/_app/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AppGroupsCreateRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/privacy/': {
      id: '/_app/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof AppPrivacyIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profiles/': {
      id: '/_app/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AppProfilesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rulesets/': {
      id: '/_app/rulesets/'
      path: '/rulesets'
      fullPath: '/rulesets/'
      preLoaderRoute: typeof AppRulesetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rulesets/$rulesetSlug': {
      id: '/_app/rulesets/$rulesetSlug'
      path: '/rulesets/$rulesetSlug'
      fullPath: '/rulesets/$rulesetSlug'
      preLoaderRoute: typeof AppRulesetsRulesetSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rulesets/create': {
      id: '/_app/rulesets/create'
      path: '/rulesets/create'
      fullPath: '/rulesets/create'
      preLoaderRoute: typeof AppRulesetsCreateRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/preview/sheet/$factionSlug': {
      id: '/preview/sheet/$factionSlug'
      path: '/preview/sheet/$factionSlug'
      fullPath: '/preview/sheet/$factionSlug'
      preLoaderRoute: typeof PreviewSheetFactionSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/assets/$type/': {
      id: '/_app/assets/$type/'
      path: '/assets/$type'
      fullPath: '/assets/$type/'
      preLoaderRoute: typeof AppAssetsTypeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/factions/$factionId/': {
      id: '/_app/factions/$factionId/'
      path: '/factions/$factionId'
      fullPath: '/factions/$factionId/'
      preLoaderRoute: typeof AppFactionsFactionIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/factions/$factionId/edit': {
      id: '/_app/factions/$factionId/edit'
      path: '/factions/$factionId/edit'
      fullPath: '/factions/$factionId/edit'
      preLoaderRoute: typeof AppFactionsFactionIdEditRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/groups/$groupSlug/': {
      id: '/_app/groups/$groupSlug/'
      path: '/'
      fullPath: '/groups/$groupSlug/'
      preLoaderRoute: typeof AppGroupsGroupSlugIndexRouteImport
      parentRoute: typeof AppGroupsGroupSlugRouteRoute
    }
    '/_app/groups/$groupSlug/edit': {
      id: '/_app/groups/$groupSlug/edit'
      path: '/edit'
      fullPath: '/groups/$groupSlug/edit'
      preLoaderRoute: typeof AppGroupsGroupSlugEditRouteRouteImport
      parentRoute: typeof AppGroupsGroupSlugRouteRoute
    }
    '/_app/profiles/$profileSlug/': {
      id: '/_app/profiles/$profileSlug/'
      path: '/profiles/$profileSlug'
      fullPath: '/profiles/$profileSlug/'
      preLoaderRoute: typeof AppProfilesProfileSlugIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profiles/$profileSlug/delete': {
      id: '/_app/profiles/$profileSlug/delete'
      path: '/profiles/$profileSlug/delete'
      fullPath: '/profiles/$profileSlug/delete'
      preLoaderRoute: typeof AppProfilesProfileSlugDeleteRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profiles/$profileSlug/edit': {
      id: '/_app/profiles/$profileSlug/edit'
      path: '/profiles/$profileSlug/edit'
      fullPath: '/profiles/$profileSlug/edit'
      preLoaderRoute: typeof AppProfilesProfileSlugEditRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rulesets/$rulesetSlug/': {
      id: '/_app/rulesets/$rulesetSlug/'
      path: '/'
      fullPath: '/rulesets/$rulesetSlug/'
      preLoaderRoute: typeof AppRulesetsRulesetSlugIndexRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRouteRoute
    }
    '/_app/rulesets/$rulesetSlug/edit': {
      id: '/_app/rulesets/$rulesetSlug/edit'
      path: '/edit'
      fullPath: '/rulesets/$rulesetSlug/edit'
      preLoaderRoute: typeof AppRulesetsRulesetSlugEditRouteRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRouteRoute
    }
    '/_app/assets/$type/$slug/': {
      id: '/_app/assets/$type/$slug/'
      path: '/assets/$type/$slug'
      fullPath: '/assets/$type/$slug/'
      preLoaderRoute: typeof AppAssetsTypeSlugIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/assets/$type/create/': {
      id: '/_app/assets/$type/create/'
      path: '/assets/$type/create'
      fullPath: '/assets/$type/create/'
      preLoaderRoute: typeof AppAssetsTypeCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rulesets/$rulesetSlug/faq/$questionSlug': {
      id: '/_app/rulesets/$rulesetSlug/faq/$questionSlug'
      path: '/faq/$questionSlug'
      fullPath: '/rulesets/$rulesetSlug/faq/$questionSlug'
      preLoaderRoute: typeof AppRulesetsRulesetSlugFaqQuestionSlugRouteRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRouteRoute
    }
    '/_app/rulesets/$rulesetSlug/faq/create': {
      id: '/_app/rulesets/$rulesetSlug/faq/create'
      path: '/faq/create'
      fullPath: '/rulesets/$rulesetSlug/faq/create'
      preLoaderRoute: typeof AppRulesetsRulesetSlugFaqCreateRouteRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRouteRoute
    }
    '/_app/rulesets/$rulesetSlug/rulebooks/create': {
      id: '/_app/rulesets/$rulesetSlug/rulebooks/create'
      path: '/rulebooks/create'
      fullPath: '/rulesets/$rulesetSlug/rulebooks/create'
      preLoaderRoute: typeof AppRulesetsRulesetSlugRulebooksCreateRouteRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRouteRoute
    }
    '/_app/assets/$type/$slug/edit/': {
      id: '/_app/assets/$type/$slug/edit/'
      path: '/assets/$type/$slug/edit'
      fullPath: '/assets/$type/$slug/edit/'
      preLoaderRoute: typeof AppAssetsTypeSlugEditIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/': {
      id: '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/'
      path: '/rulebooks/$rulebookSlug'
      fullPath: '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/'
      preLoaderRoute: typeof AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRouteRoute
    }
    '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit': {
      id: '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit'
      path: '/rulebooks/$rulebookSlug/edit'
      fullPath: '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/edit'
      preLoaderRoute: typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRouteRoute
    }
    '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions': {
      id: '/_app/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions'
      path: '/rulebooks/$rulebookSlug/editions'
      fullPath: '/rulesets/$rulesetSlug/rulebooks/$rulebookSlug/editions'
      preLoaderRoute: typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRouteImport
      parentRoute: typeof AppRulesetsRulesetSlugRouteRoute
    }
  }
}

interface AppGroupsGroupSlugRouteRouteChildren {
  AppGroupsGroupSlugEditRouteRoute: typeof AppGroupsGroupSlugEditRouteRoute
  AppGroupsGroupSlugIndexRoute: typeof AppGroupsGroupSlugIndexRoute
}

const AppGroupsGroupSlugRouteRouteChildren: AppGroupsGroupSlugRouteRouteChildren =
  {
    AppGroupsGroupSlugEditRouteRoute: AppGroupsGroupSlugEditRouteRoute,
    AppGroupsGroupSlugIndexRoute: AppGroupsGroupSlugIndexRoute,
  }

const AppGroupsGroupSlugRouteRouteWithChildren =
  AppGroupsGroupSlugRouteRoute._addFileChildren(
    AppGroupsGroupSlugRouteRouteChildren,
  )

interface AppRulesetsRulesetSlugRouteRouteChildren {
  AppRulesetsRulesetSlugEditRouteRoute: typeof AppRulesetsRulesetSlugEditRouteRoute
  AppRulesetsRulesetSlugIndexRoute: typeof AppRulesetsRulesetSlugIndexRoute
  AppRulesetsRulesetSlugFaqQuestionSlugRouteRoute: typeof AppRulesetsRulesetSlugFaqQuestionSlugRouteRoute
  AppRulesetsRulesetSlugFaqCreateRouteRoute: typeof AppRulesetsRulesetSlugFaqCreateRouteRoute
  AppRulesetsRulesetSlugRulebooksCreateRouteRoute: typeof AppRulesetsRulesetSlugRulebooksCreateRouteRoute
  AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRoute: typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRoute
  AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRoute: typeof AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRoute
  AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRoute: typeof AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRoute
}

const AppRulesetsRulesetSlugRouteRouteChildren: AppRulesetsRulesetSlugRouteRouteChildren =
  {
    AppRulesetsRulesetSlugEditRouteRoute: AppRulesetsRulesetSlugEditRouteRoute,
    AppRulesetsRulesetSlugIndexRoute: AppRulesetsRulesetSlugIndexRoute,
    AppRulesetsRulesetSlugFaqQuestionSlugRouteRoute:
      AppRulesetsRulesetSlugFaqQuestionSlugRouteRoute,
    AppRulesetsRulesetSlugFaqCreateRouteRoute:
      AppRulesetsRulesetSlugFaqCreateRouteRoute,
    AppRulesetsRulesetSlugRulebooksCreateRouteRoute:
      AppRulesetsRulesetSlugRulebooksCreateRouteRoute,
    AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRoute:
      AppRulesetsRulesetSlugRulebooksRulebookSlugEditRouteRoute,
    AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRoute:
      AppRulesetsRulesetSlugRulebooksRulebookSlugEditionsRouteRoute,
    AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRoute:
      AppRulesetsRulesetSlugRulebooksRulebookSlugIndexRoute,
  }

const AppRulesetsRulesetSlugRouteRouteWithChildren =
  AppRulesetsRulesetSlugRouteRoute._addFileChildren(
    AppRulesetsRulesetSlugRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppSplatRouteRoute: typeof AppSplatRouteRoute
  App_iconsRouteRoute: typeof App_iconsRouteRoute
  App_jobsRouteRoute: typeof App_jobsRouteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminMigrationsRouteRoute: typeof AppAdminMigrationsRouteRoute
  AppAuthErrorRouteRoute: typeof AppAuthErrorRouteRoute
  AppAuthLoginRouteRoute: typeof AppAuthLoginRouteRoute
  AppFactionsCreateRouteRoute: typeof AppFactionsCreateRouteRoute
  AppGroupsGroupSlugRouteRoute: typeof AppGroupsGroupSlugRouteRouteWithChildren
  AppGroupsCreateRouteRoute: typeof AppGroupsCreateRouteRoute
  AppRulesetsRulesetSlugRouteRoute: typeof AppRulesetsRulesetSlugRouteRouteWithChildren
  AppRulesetsCreateRouteRoute: typeof AppRulesetsCreateRouteRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppAuthIndexRoute: typeof AppAuthIndexRoute
  AppFactionsIndexRoute: typeof AppFactionsIndexRoute
  AppFuturePlansIndexRoute: typeof AppFuturePlansIndexRoute
  AppPrivacyIndexRoute: typeof AppPrivacyIndexRoute
  AppProfilesIndexRoute: typeof AppProfilesIndexRoute
  AppRulesetsIndexRoute: typeof AppRulesetsIndexRoute
  AppFactionsFactionIdEditRouteRoute: typeof AppFactionsFactionIdEditRouteRoute
  AppProfilesProfileSlugDeleteRouteRoute: typeof AppProfilesProfileSlugDeleteRouteRoute
  AppProfilesProfileSlugEditRouteRoute: typeof AppProfilesProfileSlugEditRouteRoute
  AppAssetsTypeIndexRoute: typeof AppAssetsTypeIndexRoute
  AppFactionsFactionIdIndexRoute: typeof AppFactionsFactionIdIndexRoute
  AppProfilesProfileSlugIndexRoute: typeof AppProfilesProfileSlugIndexRoute
  AppAssetsTypeSlugIndexRoute: typeof AppAssetsTypeSlugIndexRoute
  AppAssetsTypeCreateIndexRoute: typeof AppAssetsTypeCreateIndexRoute
  AppAssetsTypeSlugEditIndexRoute: typeof AppAssetsTypeSlugEditIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSplatRouteRoute: AppSplatRouteRoute,
  App_iconsRouteRoute: App_iconsRouteRoute,
  App_jobsRouteRoute: App_jobsRouteRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminMigrationsRouteRoute: AppAdminMigrationsRouteRoute,
  AppAuthErrorRouteRoute: AppAuthErrorRouteRoute,
  AppAuthLoginRouteRoute: AppAuthLoginRouteRoute,
  AppFactionsCreateRouteRoute: AppFactionsCreateRouteRoute,
  AppGroupsGroupSlugRouteRoute: AppGroupsGroupSlugRouteRouteWithChildren,
  AppGroupsCreateRouteRoute: AppGroupsCreateRouteRoute,
  AppRulesetsRulesetSlugRouteRoute:
    AppRulesetsRulesetSlugRouteRouteWithChildren,
  AppRulesetsCreateRouteRoute: AppRulesetsCreateRouteRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppAuthIndexRoute: AppAuthIndexRoute,
  AppFactionsIndexRoute: AppFactionsIndexRoute,
  AppFuturePlansIndexRoute: AppFuturePlansIndexRoute,
  AppPrivacyIndexRoute: AppPrivacyIndexRoute,
  AppProfilesIndexRoute: AppProfilesIndexRoute,
  AppRulesetsIndexRoute: AppRulesetsIndexRoute,
  AppFactionsFactionIdEditRouteRoute: AppFactionsFactionIdEditRouteRoute,
  AppProfilesProfileSlugDeleteRouteRoute:
    AppProfilesProfileSlugDeleteRouteRoute,
  AppProfilesProfileSlugEditRouteRoute: AppProfilesProfileSlugEditRouteRoute,
  AppAssetsTypeIndexRoute: AppAssetsTypeIndexRoute,
  AppFactionsFactionIdIndexRoute: AppFactionsFactionIdIndexRoute,
  AppProfilesProfileSlugIndexRoute: AppProfilesProfileSlugIndexRoute,
  AppAssetsTypeSlugIndexRoute: AppAssetsTypeSlugIndexRoute,
  AppAssetsTypeCreateIndexRoute: AppAssetsTypeCreateIndexRoute,
  AppAssetsTypeSlugEditIndexRoute: AppAssetsTypeSlugEditIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthOauthRouteRoute: AuthOauthRouteRoute,
  PreviewSheetFactionSlugRouteRoute: PreviewSheetFactionSlugRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
