/**
 * Builds and writes `media/raster.lock.json` and `src/shared/media/map.generated.ts` from the raster originals under media/ (#1888).
 * `bun run media:lock` and `bun run media:sync` both write the lock through here.
 *
 * An entry whose bytes are unchanged is kept as it is, so only new or changed files are decoded.
 * A source that is tracked but outside a sparse checkout keeps its existing entry.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { format } from 'oxfmt';
import type { FormatConfig } from 'oxfmt';
import sharp from 'sharp';

import { RASTER_SOURCE, buildMediaMap } from '../../src/shared/media/rasterLock';
import type { RasterLock, RasterLockEntry } from '../../src/shared/media/rasterLock';
import { tierRecipes } from '../media-variants';

const repoRoot = path.resolve(import.meta.dirname, '../..');
const lockPath = path.join(repoRoot, 'media/raster.lock.json');
const mapPath = path.join(repoRoot, 'src/shared/media/map.generated.ts');

export function readRasterLock(): RasterLock {
  return existsSync(lockPath) ? (JSON.parse(readFileSync(lockPath, 'utf8')) as RasterLock) : {};
}

const mediaRoot = path.join(repoRoot, 'media');

/** The checked-out path of an asset key, such as `media/image/texture/021.jpg`, refusing a key that would leave media/. */
export function sourcePath(key: string): string {
  const resolved = path.resolve(mediaRoot, `.${key}`);
  if (!resolved.startsWith(`${mediaRoot}${path.sep}`)) {
    throw new Error(`${key} is not a path under media/`);
  }
  return resolved;
}

/* Tracked sources plus new ones not yet added, so a fresh file is locked before its first commit. */
function listSources(): string[] {
  return execFileSync('/usr/bin/git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard', '--', 'media'], {
    cwd: repoRoot,
    encoding: 'utf8',
  })
    .split('\0')
    .filter((file) => RASTER_SOURCE.test(file));
}

async function describe(key: string, previous: RasterLock): Promise<RasterLockEntry> {
  const absolute = sourcePath(key);
  const kept = previous[key];
  if (!existsSync(absolute)) {
    if (!kept) {
      throw new Error(`${key} is not checked out and has no lock entry yet`);
    }
    return kept;
  }
  const bytes = readFileSync(absolute);
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  if (kept?.sha256 === sha256 && kept.bytes === bytes.length) {
    return kept;
  }
  const image = sharp(bytes);
  const [metadata, stats] = await Promise.all([image.metadata(), image.stats()]);
  if (!metadata.width || !metadata.height || (metadata.format !== 'png' && metadata.format !== 'jpeg')) {
    throw new Error(`Cannot read ${key} as a PNG or JPEG`);
  }
  const { r, g, b } = stats.dominant;
  return {
    sha256,
    bytes: bytes.length,
    width: metadata.width,
    height: metadata.height,
    format: metadata.format,
    isOpaque: stats.isOpaque,
    color: `#${[r, g, b].map((channel) => channel.toString(16).padStart(2, '0')).join('')}`,
  };
}

/** Describes every raster source under media/, reusing the previous entry of each unchanged file. */
export async function buildRasterLock(previous: RasterLock): Promise<RasterLock> {
  const lock: RasterLock = {};
  const keys = [...new Set(listSources())]
    .sort((left, right) => left.localeCompare(right))
    .map((file) => `/${path.posix.relative('media', file)}`);
  const queue = [...keys];
  async function worker(): Promise<void> {
    const key = queue.shift();
    if (key === undefined) {
      return;
    }
    lock[key] = await describe(key, previous);
    return worker();
  }
  await Promise.all(Array.from({ length: 8 }, worker));
  /* Workers finish out of order, so the keys are put back in sorted order. */
  return Object.fromEntries(keys.map((key) => [key, lock[key]]));
}

async function formatted(target: string, source: string, formatOptions: FormatConfig): Promise<string> {
  const result = await format(path.basename(target), source, formatOptions);
  if (result.errors.length > 0) {
    throw new Error(`${target} did not format: ${result.errors.map((error) => error.message).join('; ')}`);
  }
  return result.code;
}

/** Writes the lock and the committed map derived from it, formatting both first so a failure leaves neither changed. */
export async function writeRasterLock(lock: RasterLock): Promise<void> {
  const { $schema: _schema, ...formatOptions } = JSON.parse(
    readFileSync(path.join(repoRoot, '.oxfmtrc.json'), 'utf8')
  ) as FormatConfig & { $schema?: string };
  const lockSource = await formatted(lockPath, `${JSON.stringify(lock, null, 2)}\n`, formatOptions);
  const mapSource = await formatted(
    mapPath,
    `// Generated by scripts/media-lock.ts from media/raster.lock.json. Do not edit; run \`bun run media:lock\`.\n` +
      `import type { MediaMapEntry, MediaRecipes } from './rasterLock';\n\n` +
      `/** The recipe name of each size tier by category, for the installed encoder (sharp, libvips and mozjpeg versions). */\n` +
      `export const MEDIA_RECIPES: Readonly<Record<string, MediaRecipes>> = ${JSON.stringify(tierRecipes(sharp.versions), null, 2)};\n\n` +
      `export const MEDIA_MAP: Readonly<Record<string, MediaMapEntry>> = ${JSON.stringify(buildMediaMap(lock), null, 2)};\n`,
    formatOptions
  );
  writeFileSync(lockPath, lockSource);
  writeFileSync(mapPath, mapSource);
}

/** The keys whose original is new or changed since the previous lock, and the keys it no longer lists. */
export function lockChanges(previous: RasterLock, lock: RasterLock): { changed: string[]; removed: string[] } {
  return {
    changed: Object.keys(lock).filter((key) => previous[key]?.sha256 !== lock[key].sha256),
    removed: Object.keys(previous).filter((key) => !(key in lock)),
  };
}
