/**
 * Writes `media/raster.lock.json` and `src/shared/media/map.generated.ts` from the raster originals under media/ (#1888).
 *
 * Bun run media:lock
 *
 * Run it after adding or changing a raster source.
 * An entry whose bytes are unchanged is kept as it is, so only new or changed files are decoded.
 * A source that is tracked but outside a sparse checkout keeps its existing entry.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { format } from 'oxfmt';
import type { FormatConfig } from 'oxfmt';
import sharp from 'sharp';

import { RASTER_SOURCE, buildMediaMap } from '../src/shared/media/rasterLock';
import type { RasterLock, RasterLockEntry } from '../src/shared/media/rasterLock';

const repoRoot = path.resolve(import.meta.dirname, '..');
const lockPath = path.join(repoRoot, 'media/raster.lock.json');
const mapPath = path.join(repoRoot, 'src/shared/media/map.generated.ts');

const previous: RasterLock = existsSync(lockPath) ? JSON.parse(readFileSync(lockPath, 'utf8')) : {};

/* Tracked sources plus new ones not yet added, so a fresh file is locked before its first commit. */
const listed = execFileSync(
  '/usr/bin/git',
  ['ls-files', '-z', '--cached', '--others', '--exclude-standard', '--', 'media'],
  { cwd: repoRoot, encoding: 'utf8' }
)
  .split('\0')
  .filter((file) => RASTER_SOURCE.test(file));

async function describe(file: string, key: string): Promise<RasterLockEntry> {
  const absolute = path.join(repoRoot, file);
  if (!existsSync(absolute)) {
    const kept = previous[key];
    if (!kept) {
      throw new Error(`${key} is not checked out and has no lock entry yet`);
    }
    return kept;
  }
  const bytes = readFileSync(absolute);
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  const kept = previous[key];
  if (kept?.sha256 === sha256 && kept.bytes === bytes.length) {
    return kept;
  }
  const image = sharp(bytes);
  const [metadata, stats] = await Promise.all([image.metadata(), image.stats()]);
  if (!metadata.width || !metadata.height || (metadata.format !== 'png' && metadata.format !== 'jpeg')) {
    throw new Error(`Cannot read ${key} as a PNG or JPEG`);
  }
  const { r, g, b } = stats.dominant;
  return {
    sha256,
    bytes: bytes.length,
    width: metadata.width,
    height: metadata.height,
    format: metadata.format,
    isOpaque: stats.isOpaque,
    color: `#${[r, g, b].map((channel) => channel.toString(16).padStart(2, '0')).join('')}`,
  };
}

const lock: RasterLock = {};
const files = [...new Set(listed)].sort((left, right) => left.localeCompare(right));
const CONCURRENCY = 8;
for (let index = 0; index < files.length; index += CONCURRENCY) {
  const batch = files.slice(index, index + CONCURRENCY).map((file) => `/${path.posix.relative('media', file)}`);
  const entries = await Promise.all(batch.map((key) => describe(`media${key}`, key)));
  batch.forEach((key, position) => {
    lock[key] = entries[position];
  });
}

const { $schema: _schema, ...formatOptions } = JSON.parse(
  readFileSync(path.join(repoRoot, '.oxfmtrc.json'), 'utf8')
) as FormatConfig & { $schema?: string };
async function write(target: string, source: string) {
  const result = await format(path.basename(target), source, formatOptions);
  if (result.errors.length > 0) {
    throw new Error(`${target} did not format: ${result.errors.map((error) => error.message).join('; ')}`);
  }
  writeFileSync(target, result.code);
}

await write(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
await write(
  mapPath,
  `// Generated by scripts/media-lock.ts from media/raster.lock.json. Do not edit; run \`bun run media:lock\`.\n` +
    `import type { MediaMapEntry } from './rasterLock';\n\n` +
    `export const MEDIA_MAP: Readonly<Record<string, MediaMapEntry>> = ${JSON.stringify(buildMediaMap(lock), null, 2)};\n`
);

const changed = Object.keys(lock).filter((key) => previous[key]?.sha256 !== lock[key].sha256);
const removed = Object.keys(previous).filter((key) => !(key in lock));
console.log(JSON.stringify({ entries: Object.keys(lock).length, changed: changed.length, removed: removed.length }));
